site_name: Anaysis Plot Panel documentation
nav:
    - Home: home.md
    - Installation: installation.md
# Enabling LaTeX math equations
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - admonition

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    watch:
      - src/analysis_plot_panel
