site_name: Anaysis Plot Panel
nav:
    - Home: index.md
    - Installation: installation.md
# Enabling LaTeX math equations
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - admonition
    - toc:
        permalink: "#"

repo_url: https://github.com/LQG-EPFL/analysis_plot_panel


plugins:
- search
